import { StyleSheet } from 'react-native';

import { MIN_TOUCH_TARGET } from '@/constants/touchTargets';
import { Theme } from '@/constants/Theme';

/**
 * Shared “hub discover” chrome for Journey and Progress (chips, timeframe strip, quest rows).
 */
export const journeyHubStyles = StyleSheet.create({
  root: { width: '100%', overflow: 'hidden', backgroundColor: Theme.bg },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
  },
  sectionHeadText: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.2,
    color: Theme.textMuted,
  },
  chipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 8,
    paddingBottom: 12,
  },
  chipsRowFlush: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 16,
    paddingBottom: 12,
  },
  chipsScroll: { flexGrow: 1, flexShrink: 1, maxWidth: '100%' },
  chips: { gap: 6, alignItems: 'center', flexGrow: 0 },
  chipHeartWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Theme.accentSoft,
    borderWidth: 1,
    borderColor: Theme.border,
    flexShrink: 0,
  },
  // Category chips carry their category's icon and colour, matching the Explore
  // map markers, so the same category looks the same in both places. The
  // selected chip fills with the category colour (callers pass it inline, since
  // it differs per category) rather than tinting faintly.
  //
  // Sized so all four fit one row without scrolling, down to a 360dp screen:
  // measured label widths total 165px, leaving 13px spare there. Adding a
  // longer category name would push them back into a scroll, so check the fit
  // if the catalog ever gains one.
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minHeight: MIN_TOUCH_TARGET,
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: Theme.surface,
  },
  chipText: { fontSize: 12, fontFamily: 'Inter_700Bold', fontWeight: '700', color: Theme.text },
  discoverBlock: { width: '100%', paddingBottom: 8 },
  heroCard: {
    marginHorizontal: 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: Theme.surface,
  },
  heroSolid: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.border,
  },
  heroHeadline: {
    marginTop: 4,
    fontSize: 18,
    fontFamily: 'Fraunces_700Bold',
    fontWeight: '700',
    color: '#fff',
    lineHeight: 22,
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  heroHint: {
    marginTop: 8,
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
    lineHeight: 18,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.92)',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  heroEmptyTitle: { fontSize: 16, fontFamily: 'Inter_600SemiBold', fontWeight: '600', color: Theme.text },
  heroEmptySub: {
    marginTop: 8,
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    lineHeight: 20,
    color: Theme.textMuted,
    textAlign: 'center',
  },
  heroEmptyPadded: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyTitleSolid: { fontSize: 18, fontFamily: 'Fraunces_700Bold', fontWeight: '700', color: Theme.text, textAlign: 'center' },
  emptyBodySolid: {
    marginTop: 8,
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    lineHeight: 20,
    color: Theme.textMuted,
    textAlign: 'center',
  },
  timeframeSection: { marginBottom: 20 },
  timeframeSplit: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    marginHorizontal: 16,
  },
  timeframeImageCol: {
    width: '38%',
    maxWidth: 148,
    minWidth: 108,
    alignSelf: 'stretch',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: Theme.surface,
  },
  timeframeImageBg: {
    flex: 1,
    width: '100%',
    minHeight: 200,
  },
  timeframeImageLabels: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  timeframeQuestCol: { flex: 1, gap: 10, minWidth: 0, justifyContent: 'center' },
  discoverQuestRow: {
    flexDirection: 'row',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.border,
    backgroundColor: Theme.surface,
    overflow: 'hidden',
  },
  discoverQuestAccent: { width: 4 },
  discoverQuestRowBody: { flex: 1, padding: 12, gap: 6, minWidth: 0 },
  questRowMeta: {
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    color: Theme.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  questRowMetaLight: { fontSize: 12, fontFamily: 'Inter_500Medium', fontWeight: '500', color: Theme.textMuted },
  // Fraunces, not Inter. This is the one line in the app that is the product —
  // a quest's name is what someone reads and decides on — and leaving it in the
  // body face made every card look like a settings row. Line height is a point
  // looser than the sans version needed: the serif's ascenders crowd otherwise.
  questRowTitle: {
    fontSize: 17,
    fontFamily: 'Fraunces_600SemiBold',
    color: Theme.text,
    lineHeight: 23,
  },
  questRowSub: { fontSize: 14, fontFamily: 'Inter_400Regular', lineHeight: 20, color: Theme.textMuted },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  // Brand amber, carrying dark text at 6.61:1. Amber is a fill here and never a
  // foreground — see the note on `accentWarm` in constants/Theme.ts.
  newBadge: {
    backgroundColor: Theme.accentWarm,
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  newBadgeText: {
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    letterSpacing: 0.6,
    color: Theme.accentWarmText,
  },
  questRowActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 4 },
  likedSectionLabel: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 4,
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.2,
    color: Theme.textMuted,
  },
  likedListContent: { paddingBottom: 12 },
  likedCompactRow: {
    flexDirection: 'row',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.border,
    backgroundColor: Theme.surface,
    overflow: 'hidden',
    minHeight: 120,
  },
  likedThumb: { width: 88, minHeight: 120, backgroundColor: Theme.bg },
  likedCompactBody: { flex: 1, padding: 12, gap: 6, justifyContent: 'center', minWidth: 0 },
  panel: { width: '100%', overflow: 'hidden' },
  card: { position: 'relative', overflow: 'hidden' },
  fill: { ...StyleSheet.absoluteFillObject },
  bgImage: { width: '100%', height: '100%' },
  scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(44,40,37,0.24)' },
  scrimStrong: { backgroundColor: 'rgba(44,40,37,0.52)' },
  footerMeta: {
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.92)',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  btnSubtleSolid: {
    // Was a hardcoded rgba copy of the old accent, so it kept the previous
    // green when the palette changed. Reads from the token now.
    backgroundColor: Theme.accent,
    borderRadius: 999,
    minHeight: MIN_TOUCH_TARGET,
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 14,
  },
  btnSubtleSolidText: { color: '#fff', fontSize: 12, fontFamily: 'Inter_600SemiBold', fontWeight: '600' },
  btnSubtleLight: {
    borderRadius: 999,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.border,
    minHeight: MIN_TOUCH_TARGET,
    paddingVertical: 6,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  btnSubtleLightText: { color: Theme.accent, fontWeight: '600', fontSize: 12, fontFamily: 'Inter_600SemiBold' },
  busyRow: { alignItems: 'center', paddingVertical: 8 },
  pressed: { opacity: 0.9 },
  disabled: { opacity: 0.45 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: Theme.surface,
    borderRadius: 16,
    padding: 16,
    maxHeight: '80%',
  },
  modalTitle: { fontSize: 18, fontFamily: 'Fraunces_700Bold', fontWeight: '800', color: Theme.text, marginBottom: 8 },
  modalBody: { fontSize: 14, fontFamily: 'Inter_400Regular', lineHeight: 20, color: Theme.textMuted, marginBottom: 12 },
  modalSub: { fontSize: 13, fontFamily: 'Inter_700Bold', fontWeight: '700', color: Theme.text, marginBottom: 8 },
  modalList: { maxHeight: 220, marginBottom: 12 },
  modalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.border,
    backgroundColor: Theme.bg,
  },
  modalRowTitle: { flex: 1, fontSize: 14, fontFamily: 'Inter_700Bold', fontWeight: '700', color: Theme.text, marginRight: 12 },
  modalRowAction: { fontSize: 13, fontFamily: 'Inter_700Bold', fontWeight: '800', color: Theme.accent },
  modalClose: { alignSelf: 'center', paddingVertical: 10 },
  modalCloseText: { fontSize: 15, fontFamily: 'Inter_700Bold', fontWeight: '700', color: Theme.textMuted },
  likedInfoCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: Theme.surface,
    borderRadius: 16,
    padding: 18,
  },
  likedInfoIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Theme.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    alignSelf: 'center',
  },
  likedInfoTitle: { fontSize: 18, fontFamily: 'Fraunces_700Bold', fontWeight: '800', color: Theme.text, marginBottom: 8 },
  likedInfoBody: { fontSize: 14, fontFamily: 'Inter_400Regular', lineHeight: 20, color: Theme.textMuted, marginBottom: 16 },
  likedInfoClose: { alignSelf: 'center', paddingVertical: 10, paddingHorizontal: 16 },
  likedInfoCloseText: { fontSize: 15, fontFamily: 'Inter_700Bold', fontWeight: '700', color: Theme.accent },
});
