import { StyleSheet } from 'react-native';

import { Theme } from '@/constants/Theme';

/** Shared chrome for the guided-runner interaction blocks. */
export const stepInteractionStyles = StyleSheet.create({
  block: { gap: 12 },
  prompt: {
    fontSize: 15,
    fontFamily: 'Inter_600SemiBold',
    lineHeight: 21,
    fontWeight: '600',
    color: Theme.text,
  },
  helper: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
    color: Theme.textMuted,
  },
  input: {
    minHeight: 96,
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    fontFamily: 'Inter_400Regular',
    lineHeight: 21,
    color: Theme.text,
    backgroundColor: Theme.bg,
  },
  inputSingle: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    fontFamily: 'Inter_400Regular',
    color: Theme.text,
    backgroundColor: Theme.bg,
  },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: Theme.border,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  clock: {
    fontSize: 44,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    color: Theme.text,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  clockCaption: {
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    color: Theme.textMuted,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: Theme.bg,
  },
  itemIndex: { fontSize: 13, fontFamily: 'Inter_700Bold', fontWeight: '700', width: 20, textAlign: 'center' },
  itemText: { flex: 1, fontSize: 15, fontFamily: 'Inter_400Regular', color: Theme.text },
  itemRemove: { padding: 4 },
  addRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  addBtn: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: Theme.accentSoft,
    borderWidth: 1,
    borderColor: Theme.accent,
  },
  addBtnText: { color: Theme.accent, fontWeight: '700', fontSize: 14, fontFamily: 'Inter_700Bold' },
  photoPreview: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: 12,
    backgroundColor: Theme.border,
  },
  photoActionsRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  secondaryBtn: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.border,
  },
  secondaryBtnText: { color: Theme.accent, fontWeight: '600', fontSize: 14, fontFamily: 'Inter_600SemiBold' },
  pressed: { opacity: 0.85 },
  disabled: { opacity: 0.5 },
  timerResetLink: { alignSelf: 'center', paddingVertical: 8, paddingHorizontal: 4 },
  timerResetLinkText: { color: Theme.danger, fontWeight: '600', fontSize: 14, fontFamily: 'Inter_600SemiBold' },
});
